export const isoCountries = {
    'AF' : 'Afghanistan',
    'AX' : 'Aland Islands',
    'AL' : 'Albania',
    'DZ' : 'Algeria',
    'AS' : 'American Samoa',
    'AD' : 'Andorra',
    'AO' : 'Angola',
    'AI' : 'Anguilla',
    'AQ' : 'Antarctica',
    'AG' : 'Antigua And Barbuda',
    'AR' : 'Argentina',
    'AM' : 'Armenia',
    'AW' : 'Aruba',
    'AU' : 'Australia',
    'AT' : 'Austria',
    'AZ' : 'Azerbaijan',
    'BS' : 'Bahamas',
    'BH' : 'Bahrain',
    'BD' : 'Bangladesh',
    'BB' : 'Barbados',
    'BY' : 'Belarus',
    'BE' : 'Belgium',
    'BZ' : 'Belize',
    'BJ' : 'Benin',
    'BM' : 'Bermuda',
    'BT' : 'Bhutan',
    'BO' : 'Bolivia',
    'BA' : 'Bosnia And Herzegovina',
    'BW' : 'Botswana',
    'BV' : 'Bouvet Island',
    'BR' : 'Brazil',
    'IO' : 'British Indian Ocean Territory',
    'BN' : 'Brunei Darussalam',
    'BG' : 'Bulgaria',
    'BF' : 'Burkina Faso',
    'BI' : 'Burundi',
    'KH' : 'Cambodia',
    'CM' : 'Cameroon',
    'CA' : 'Canada',
    'CV' : 'Cape Verde',
    'KY' : 'Cayman Islands',
    'CF' : 'Central African Republic',
    'TD' : 'Chad',
    'CL' : 'Chile',
    'CN' : 'China',
    'CX' : 'Christmas Island',
    'CC' : 'Cocos (Keeling) Islands',
    'CO' : 'Colombia',
    'KM' : 'Comoros',
    'CG' : 'Congo',
    'CD' : 'Congo, Democratic Republic',
    'CK' : 'Cook Islands',
    'CR' : 'Costa Rica',
    'CI' : 'Cote D\'Ivoire',
    'HR' : 'Croatia',
    'CU' : 'Cuba',
    'CY' : 'Cyprus',
    'CZ' : 'Czech Republic',
    'DK' : 'Denmark',
    'DJ' : 'Djibouti',
    'DM' : 'Dominica',
    'DO' : 'Dominican Republic',
    'EC' : 'Ecuador',
    'EG' : 'Egypt',
    'SV' : 'El Salvador',
    'GQ' : 'Equatorial Guinea',
    'ER' : 'Eritrea',
    'EE' : 'Estonia',
    'ET' : 'Ethiopia',
    'FK' : 'Falkland Islands (Malvinas)',
    'FO' : 'Faroe Islands',
    'FJ' : 'Fiji',
    'FI' : 'Finland',
    'FR' : 'France',
    'GF' : 'French Guiana',
    'PF' : 'French Polynesia',
    'TF' : 'French Southern Territories',
    'GA' : 'Gabon',
    'GM' : 'Gambia',
    'GE' : 'Georgia',
    'DE' : 'Germany',
    'GH' : 'Ghana',
    'GI' : 'Gibraltar',
    'GR' : 'Greece',
    'GL' : 'Greenland',
    'GD' : 'Grenada',
    'GP' : 'Guadeloupe',
    'GU' : 'Guam',
    'GT' : 'Guatemala',
    'GG' : 'Guernsey',
    'GN' : 'Guinea',
    'GW' : 'Guinea-Bissau',
    'GY' : 'Guyana',
    'HT' : 'Haiti',
    'HM' : 'Heard Island & Mcdonald Islands',
    'VA' : 'Holy See (Vatican City State)',
    'HN' : 'Honduras',
    'HK' : 'Hong Kong',
    'HU' : 'Hungary',
    'IS' : 'Iceland',
    'IN' : 'India',
    'ID' : 'Indonesia',
    'IR' : 'Iran, Islamic Republic Of',
    'IQ' : 'Iraq',
    'IE' : 'Ireland',
    'IM' : 'Isle Of Man',
    'IL' : 'Israel',
    'IT' : 'Italy',
    'JM' : 'Jamaica',
    'JP' : 'Japan',
    'JE' : 'Jersey',
    'JO' : 'Jordan',
    'KZ' : 'Kazakhstan',
    'KE' : 'Kenya',
    'KI' : 'Kiribati',
    'KR' : 'Korea',
    'KW' : 'Kuwait',
    'KG' : 'Kyrgyzstan',
    'LA' : 'Lao People\'s Democratic Republic',
    'LV' : 'Latvia',
    'LB' : 'Lebanon',
    'LS' : 'Lesotho',
    'LR' : 'Liberia',
    'LY' : 'Libyan Arab Jamahiriya',
    'LI' : 'Liechtenstein',
    'LT' : 'Lithuania',
    'LU' : 'Luxembourg',
    'MO' : 'Macao',
    'MK' : 'Macedonia',
    'MG' : 'Madagascar',
    'MW' : 'Malawi',
    'MY' : 'Malaysia',
    'MV' : 'Maldives',
    'ML' : 'Mali',
    'MT' : 'Malta',
    'MH' : 'Marshall Islands',
    'MQ' : 'Martinique',
    'MR' : 'Mauritania',
    'MU' : 'Mauritius',
    'YT' : 'Mayotte',
    'MX' : 'Mexico',
    'FM' : 'Micronesia, Federated States Of',
    'MD' : 'Moldova',
    'MC' : 'Monaco',
    'MN' : 'Mongolia',
    'ME' : 'Montenegro',
    'MS' : 'Montserrat',
    'MA' : 'Morocco',
    'MZ' : 'Mozambique',
    'MM' : 'Myanmar',
    'NA' : 'Namibia',
    'NR' : 'Nauru',
    'NP' : 'Nepal',
    'NL' : 'Netherlands',
    'AN' : 'Netherlands Antilles',
    'NC' : 'New Caledonia',
    'NZ' : 'New Zealand',
    'NI' : 'Nicaragua',
    'NE' : 'Niger',
    'NG' : 'Nigeria',
    'NU' : 'Niue',
    'NF' : 'Norfolk Island',
    'MP' : 'Northern Mariana Islands',
    'NO' : 'Norway',
    'OM' : 'Oman',
    'PK' : 'Pakistan',
    'PW' : 'Palau',
    'PS' : 'Palestinian Territory, Occupied',
    'PA' : 'Panama',
    'PG' : 'Papua New Guinea',
    'PY' : 'Paraguay',
    'PE' : 'Peru',
    'PH' : 'Philippines',
    'PN' : 'Pitcairn',
    'PL' : 'Poland',
    'PT' : 'Portugal',
    'PR' : 'Puerto Rico',
    'QA' : 'Qatar',
    'RE' : 'Reunion',
    'RO' : 'Romania',
    'RU' : 'Russian Federation',
    'RW' : 'Rwanda',
    'BL' : 'Saint Barthelemy',
    'SH' : 'Saint Helena',
    'KN' : 'Saint Kitts And Nevis',
    'LC' : 'Saint Lucia',
    'MF' : 'Saint Martin',
    'PM' : 'Saint Pierre And Miquelon',
    'VC' : 'Saint Vincent And Grenadines',
    'WS' : 'Samoa',
    'SM' : 'San Marino',
    'ST' : 'Sao Tome And Principe',
    'SA' : 'Saudi Arabia',
    'SN' : 'Senegal',
    'RS' : 'Serbia',
    'SC' : 'Seychelles',
    'SL' : 'Sierra Leone',
    'SG' : 'Singapore',
    'SK' : 'Slovakia',
    'SI' : 'Slovenia',
    'SB' : 'Solomon Islands',
    'SO' : 'Somalia',
    'ZA' : 'South Africa',
    'GS' : 'South Georgia And Sandwich Isl.',
    'ES' : 'Spain',
    'LK' : 'Sri Lanka',
    'SD' : 'Sudan',
    'SR' : 'Suriname',
    'SJ' : 'Svalbard And Jan Mayen',
    'SZ' : 'Swaziland',
    'SE' : 'Sweden',
    'CH' : 'Switzerland',
    'SY' : 'Syrian Arab Republic',
    'TW' : 'Taiwan',
    'TJ' : 'Tajikistan',
    'TZ' : 'Tanzania',
    'TH' : 'Thailand',
    'TL' : 'Timor-Leste',
    'TG' : 'Togo',
    'TK' : 'Tokelau',
    'TO' : 'Tonga',
    'TT' : 'Trinidad And Tobago',
    'TN' : 'Tunisia',
    'TR' : 'Turkey',
    'TM' : 'Turkmenistan',
    'TC' : 'Turks And Caicos Islands',
    'TV' : 'Tuvalu',
    'UG' : 'Uganda',
    'UA' : 'Ukraine',
    'AE' : 'United Arab Emirates',
    'GB' : 'United Kingdom',
    'US' : 'United States',
    'UM' : 'United States Outlying Islands',
    'UY' : 'Uruguay',
    'UZ' : 'Uzbekistan',
    'VU' : 'Vanuatu',
    'VE' : 'Venezuela',
    'VN' : 'Viet Nam',
    'VG' : 'Virgin Islands, British',
    'VI' : 'Virgin Islands, U.S.',
    'WF' : 'Wallis And Futuna',
    'EH' : 'Western Sahara',
    'YE' : 'Yemen',
    'ZM' : 'Zambia',
    'ZW' : 'Zimbabwe'
};

export const isoCountriesRu = {
    'AF': 'Афганистан',
    'AX': 'Аландские острова',
    'AL': 'Албания',
    'DZ': 'Алжир',
    'AS': 'Американское Самоа',
    'AD': 'Андорра',
    'AO': 'Ангола',
    'AI': 'Ангилья',
    'AQ': 'Антарктика',
    'AG': 'Антигуа и Барбуда',
    'AR': 'Аргентина',
    'AM': 'Армения',
    'AW': 'Аруба',
    'AU': 'Австралия',
    'AT': 'Австрия',
    'AZ': 'Азербайджан',
    'BS': 'Багамы',
    'BH': 'Бахрейн',
    'BD': 'Бангладеш',
    'BB': 'Барбадос',
    'BY': 'Беларусь',
    'BE': 'Бельгия',
    'BZ': 'Белиз',
    'BJ': 'Бенин',
    'BM': 'Бермуды',
    'BT': 'Бутан',
    'BO': 'Боливия',
    'BA': 'Босния и Герцеговина',
    'BW': 'Ботсвана',
    'BV': 'Остров Буве',
    'BR': 'Бразилия',
    'IO': 'Британская территория в Индийском океане',
    'BN': 'Бруней-Даруссалам',
    'BG': 'Болгария',
    'BF': 'Буркина-Фасо',
    'BI': 'Бурунди',
    'KH': 'Камбоджа',
    'CM': 'Камерун',
    'CA': 'Канада',
    'CV': 'Кабо-Верде',
    'KY': 'Каймановы острова',
    'CF': 'Центральноафриканская Республика',
    'TD': 'Чад',
    'CL': 'Чили',
    'CN': 'Китай',
    'CX': 'Остров Рождества',
    'CC': 'Кокосовые (Килинг) острова',
    'CO': 'Колумбия',
    'KM': 'Коморы',
    'CG': 'Конго',
    'CD': 'Конго, Демократическая Республика',
    'CK': 'Острова Кука',
    'CR': 'Коста-Рика',
    'CI': "Кот-д'Ивуар",
    'HR': 'Хорватия',
    'CU': 'Куба',
    'CY': 'Кипр',
    'CZ': 'Чехия',
    'DK': 'Дания',
    'DJ': 'Джибути',
    'DM': 'Доминика',
    'DO': 'Доминиканская Республика',
    'EC': 'Эквадор',
    'EG': 'Египет',
    'SV': 'Сальвадор',
    'GQ': 'Экваториальная Гвинея',
    'ER': 'Эритрея',
    'EE': 'Эстония',
    'ET': 'Эфиопия',
    'FK': 'Фолклендские (Мальвинские) острова',
    'FO': 'Фарерские острова',
    'FJ': 'Фиджи',
    'FI': 'Финляндия',
    'FR': 'Франция',
    'GF': 'Французская Гвиана',
    'PF': 'Французская Полинезия',
    'TF': 'Французские Южные территории',
    'GA': 'Габон',
    'GM': 'Гамбия',
    'GE': 'Грузия',
    'DE': 'Германия',
    'GH': 'Гана',
    'GI': 'Гибралтар',
    'GR': 'Греция',
    'GL': 'Гренландия',
    'GD': 'Гренада',
    'GP': 'Гваделупа',
    'GU': 'Гуам',
    'GT': 'Гватемала',
    'GG': 'Гернси',
    'GN': 'Гвинея',
    'GW': 'Гвинея-Бисау',
    'GY': 'Гайана',
    'HT': 'Гаити',
    'HM': 'Остров Херд и острова Макдональд',
    'VA': 'Ватикан',
    'HN': 'Гондурас',
    'HK': 'Гонконг',
    'HU': 'Венгрия',
    'IS': 'Исландия',
    'IN': 'Индия',
    'ID': 'Индонезия',
    'IR': 'Иран',
    'IQ': 'Ирак',
    'IE': 'Ирландия',
    'IM': 'Остров Мэн',
    'IL': 'Израиль',
    'IT': 'Италия',
    'JM': 'Ямайка',
    'JP': 'Япония',
    'JE': 'Джерси',
    'JO': 'Иордания',
    'KZ': 'Казахстан',
    'KE': 'Кения',
    'KI': 'Кирибати',
    'KR': 'Южная Корея',
    'KW': 'Кувейт',
    'KG': 'Кыргызстан',
    'LA': 'Лаос',
    'LV': 'Латвия',
    'LB': 'Ливан',
    'LS': 'Лесото',
    'LR': 'Либерия',
    'LY': 'Ливия',
    'LI': 'Лихтенштейн',
    'LT': 'Литва',
    'LU': 'Люксембург',
    'MO': 'Макао',
    'MK': 'Македония',
    'MG': 'Мадагаскар',
    'MW': 'Малави',
    'MY': 'Малайзия',
    'MV': 'Мальдивы',
    'ML': 'Мали',
    'MT': 'Мальта',
    'MH': 'Маршалловы Острова',
    'MQ': 'Мартиника',
    'MR': 'Мавритания',
    'MU': 'Маврикий',
    'YT': 'Майотта',
    'MX': 'Мексика',
    'FM': 'Микронезия',
    'MD': 'Молдова',
    'MC': 'Монако',
    'MN': 'Монголия',
    'ME': 'Черногория',
    'MS': 'Монтсеррат',
    'MA': 'Марокко',
    'MZ': 'Мозамбик',
    'MM': 'Мьянма',
    'NA': 'Намибия',
    'NR': 'Науру',
    'NP': 'Непал',
    'NL': 'Нидерланды',
    'AN': 'Нидерландские Антильские острова',
    'NC': 'Новая Каледония',
    'NZ': 'Новая Зеландия',
    'NI': 'Никарагуа',
    'NE': 'Нигер',
    'NG': 'Нигерия',
    'NU': 'Ниуэ',
    'NF': 'Остров Норфолк',
    'MP': 'Северные Марианские острова',
    'NO': 'Норвегия',
    'OM': 'Оман',
    'PK': 'Пакистан',
    'PW': 'Палау',
    'PS': 'Палестинская территория',
    'PA': 'Панама',
    'PG': 'Папуа — Новая Гвинея',
    'PY': 'Парагвай',
    'PE': 'Перу',
    'PH': 'Филиппины',
    'PN': 'Питкэрн',
    'PL': 'Польша',
    'PT': 'Португалия',
    'PR': 'Пуэрто-Рико',
    'QA': 'Катар',
    'RE': 'Реюньон',
    'RO': 'Румыния',
    'RU': 'Российская Федерация',
    'RW': 'Руанда',
    'BL': 'Сен-Бартелеми',
    'SH': 'Остров Святой Елены',
    'KN': 'Сент-Китс и Невис',
    'LC': 'Сент-Люсия',
    'MF': 'Сен-Мартен',
    'PM': 'Сен-Пьер и Микелон',
    'VC': 'Сент-Винсент и Гренадины',
    'WS': 'Самоа',
    'SM': 'Сан-Марино',
    'ST': 'Сан-Томе и Принсипи',
    'SA': 'Саудовская Аравия',
    'SN': 'Сенегал',
    'RS': 'Сербия',
    'SC': 'Сейшельские Острова',
    'SL': 'Сьерра-Леоне',
    'SG': 'Сингапур',
    'SK': 'Словакия',
    'SI': 'Словения',
    'SB': 'Соломоновы Острова',
    'SO': 'Сомали',
    'ZA': 'Южно-Африканская Республика',
    'GS': 'Южная Георгия и Южные Сандвичевы острова',
    'ES': 'Испания',
    'LK': 'Шри-Ланка',
    'SD': 'Судан',
    'SR': 'Суринам',
    'SJ': 'Шпицберген и Ян-Майен',
    'SZ': 'Эсватини',
    'SE': 'Швеция',
    'CH': 'Швейцария',
    'SY': 'Сирийская Арабская Республика',
    'TW': 'Тайвань',
    'TJ': 'Таджикистан',
    'TZ': 'Танзания',
    'TH': 'Таиланд',
    'TL': 'Восточный Тимор',
    'TG': 'Того',
    'TK': 'Токелау',
    'TO': 'Тонга',
    'TT': 'Тринидад и Тобаго',
    'TN': 'Тунис',
    'TR': 'Турция',
    'TM': 'Туркменистан',
    'TC': 'Теркс и Кайкос',
    'TV': 'Тувалу',
    'UG': 'Уганда',
    'UA': 'Украина',
    'AE': 'Объединенные Арабские Эмираты',
    'GB': 'Великобритания',
    'US': 'Соединенные Штаты',
    'UM': 'Внешние малые острова США',
    'UY': 'Уругвай',
    'UZ': 'Узбекистан',
    'VU': 'Вануату',
    'VE': 'Венесуэла',
    'VN': 'Вьетнам',
    'VG': 'Виргинские острова, Британские',
    'VI': 'Виргинские острова, США',
    'WF': 'Уоллис и Футуна',
    'EH': 'Западная Сахара',
    'YE': 'Йемен',
    'ZM': 'Замбия',
    'ZW': 'Зимбабве'
};

export function getCountryName (countryCode) {
    if (isoCountries.hasOwnProperty(countryCode)) {
        return isoCountries[countryCode];
    } else {
        return countryCode;
    }
}

export function getCountryNameRu (countryCode) {
    if (isoCountries.hasOwnProperty(countryCode)) {
        return isoCountriesRu[countryCode];
    } else {
        return countryCode;
    }
}

export const isoCountriesRuOptions = [
    {value: 'AF', label: 'Афганистан'},
    {value: 'AX', label: 'Аландские острова'},
    {value: 'AL', label: 'Албания'},
    {value: 'DZ', label: 'Алжир'},
    {value: 'AS', label: 'Американское Самоа'},
    {value: 'AD', label: 'Андорра'},
    {value: 'AO', label: 'Ангола'},
    {value: 'AI', label: 'Ангилья'},
    {value: 'AQ', label: 'Антарктика'},
    {value: 'AG', label: 'Антигуа и Барбуда'},
    {value: 'AR', label: 'Аргентина'},
    {value: 'AM', label: 'Армения'},
    {value: 'AW', label: 'Аруба'},
    {value: 'AU', label: 'Австралия'},
    {value: 'AT', label: 'Австрия'},
    {value: 'AZ', label: 'Азербайджан'},
    {value: 'BS', label: 'Багамы'},
    {value: 'BH', label: 'Бахрейн'},
    {value: 'BD', label: 'Бангладеш'},
    {value: 'BB', label: 'Барбадос'},
    {value: 'BY', label: 'Беларусь'},
    {value: 'BE', label: 'Бельгия'},
    {value: 'BZ', label: 'Белиз'},
    {value: 'BJ', label: 'Бенин'},
    {value: 'BM', label: 'Бермуды'},
    {value: 'BT', label: 'Бутан'},
    {value: 'BO', label: 'Боливия'},
    {value: 'BA', label: 'Босния и Герцеговина'},
    {value: 'BW', label: 'Ботсвана'},
    {value: 'BV', label: 'Остров Буве'},
    {value: 'BR', label: 'Бразилия'},
    {value: 'IO', label: 'Британская территория в Индийском океане'},
    {value: 'BN', label: 'Бруней-Даруссалам'},
    {value: 'BG', label: 'Болгария'},
    {value: 'BF', label: 'Буркина-Фасо'},
    {value: 'BI', label: 'Бурунди'},
    {value: 'KH', label: 'Камбоджа'},
    {value: 'CM', label: 'Камерун'},
    {value: 'CA', label: 'Канада'},
    {value: 'CV', label: 'Кабо-Верде'},
    {value: 'KY', label: 'Каймановы острова'},
    {value: 'CF', label: 'Центральноафриканская Республика'},
    {value: 'TD', label: 'Чад'},
    {value: 'CL', label: 'Чили'},
    {value: 'CN', label: 'Китай'},
    {value: 'CX', label: 'Остров Рождества'},
    {value: 'CC', label: 'Кокосовые (Килинг) острова'},
    {value: 'CO', label: 'Колумбия'},
    {value: 'KM', label: 'Коморы'},
    {value: 'CG', label: 'Конго'},
    {value: 'CD', label: 'Конго, Демократическая Республика'},
    {value: 'CK', label: 'Острова Кука'},
    {value: 'CR', label: 'Коста-Рика'},
    {value: 'CI', label: "Кот-д'Ивуар"},
    {value: 'HR', label: 'Хорватия'},
    {value: 'CU', label: 'Куба'},
    {value: 'CY', label: 'Кипр'},
    {value: 'CZ', label: 'Чехия'},
    {value: 'DK', label: 'Дания'},
    {value: 'DJ', label: 'Джибути'},
    {value: 'DM', label: 'Доминика'},
    {value: 'DO', label: 'Доминиканская Республика'},
    {value: 'EC', label: 'Эквадор'},
    {value: 'EG', label: 'Египет'},
    {value: 'SV', label: 'Сальвадор'},
    {value: 'GQ', label: 'Экваториальная Гвинея'},
    {value: 'ER', label: 'Эритрея'},
    {value: 'EE', label: 'Эстония'},
    {value: 'ET', label: 'Эфиопия'},
    {value: 'FK', label: 'Фолклендские (Мальвинские) острова'},
    {value: 'FO', label: 'Фарерские острова'},
    {value: 'FJ', label: 'Фиджи'},
    {value: 'FI', label: 'Финляндия'},
    {value: 'FR', label: 'Франция'},
    {value: 'GF', label: 'Французская Гвиана'},
    {value: 'PF', label: 'Французская Полинезия'},
    {value: 'TF', label: 'Французские Южные территории'},
    {value: 'GA', label: 'Габон'},
    {value: 'GM', label: 'Гамбия'},
    {value: 'GE', label: 'Грузия'},
    {value: 'DE', label: 'Германия'},
    {value: 'GH', label: 'Гана'},
    {value: 'GI', label: 'Гибралтар'},
    {value: 'GR', label: 'Греция'},
    {value: 'GL', label: 'Гренландия'},
    {value: 'GD', label: 'Гренада'},
    {value: 'GP', label: 'Гваделупа'},
    {value: 'GU', label: 'Гуам'},
    {value: 'GT', label: 'Гватемала'},
    {value: 'GG', label: 'Гернси'},
    {value: 'GN', label: 'Гвинея'},
    {value: 'GW', label: 'Гвинея-Бисау'},
    {value: 'GY', label: 'Гайана'},
    {value: 'HT', label: 'Гаити'},
    {value: 'HM', label: 'Остров Херд и острова Макдональд'},
    {value: 'VA', label: 'Ватикан'},
    {value: 'HN', label: 'Гондурас'},
    {value: 'HK', label: 'Гонконг'},
    {value: 'HU', label: 'Венгрия'},
    {value: 'IS', label: 'Исландия'},
    {value: 'IN', label: 'Индия'},
    {value: 'ID', label: 'Индонезия'},
    {value: 'IR', label: 'Иран'},
    {value: 'IQ', label: 'Ирак'},
    {value: 'IE', label: 'Ирландия'},
    {value: 'IM', label: 'Остров Мэн'},
    {value: 'IL', label: 'Израиль'},
    {value: 'IT', label: 'Италия'},
    {value: 'JM', label: 'Ямайка'},
    {value: 'JP', label: 'Япония'},
    {value: 'JE', label: 'Джерси'},
    {value: 'JO', label: 'Иордания'},
    {value: 'KZ', label: 'Казахстан'},
    {value: 'KE', label: 'Кения'},
    {value: 'KI', label: 'Кирибати'},
    {value: 'KR', label: 'Южная Корея'},
    {value: 'KW', label: 'Кувейт'},
    {value: 'KG', label: 'Кыргызстан'},
    {value: 'LA', label: 'Лаос'},
    {value: 'LV', label: 'Латвия'},
    {value: 'LB', label: 'Ливан'},
    {value: 'LS', label: 'Лесото'},
    {value: 'LR', label: 'Либерия'},
    {value: 'LY', label: 'Ливия'},
    {value: 'LI', label: 'Лихтенштейн'},
    {value: 'LT', label: 'Литва'},
    {value: 'LU', label: 'Люксембург'},
    {value: 'MO', label: 'Макао'},
    {value: 'MK', label: 'Македония'},
    {value: 'MG', label: 'Мадагаскар'},
    {value: 'MW', label: 'Малави'},
    {value: 'MY', label: 'Малайзия'},
    {value: 'MV', label: 'Мальдивы'},
    {value: 'ML', label: 'Мали'},
    {value: 'MT', label: 'Мальта'},
    {value: 'MH', label: 'Маршалловы Острова'},
    {value: 'MQ', label: 'Мартиника'},
    {value: 'MR', label: 'Мавритания'},
    {value: 'MU', label: 'Маврикий'},
    {value: 'YT', label: 'Майотта'},
    {value: 'MX', label: 'Мексика'},
    {value: 'FM', label: 'Микронезия'},
    {value: 'MD', label: 'Молдова'},
    {value: 'MC', label: 'Монако'},
    {value: 'MN', label: 'Монголия'},
    {value: 'ME', label: 'Черногория'},
    {value: 'MS', label: 'Монтсеррат'},
    {value: 'MA', label: 'Марокко'},
    {value: 'MZ', label: 'Мозамбик'},
    {value: 'MM', label: 'Мьянма'},
    {value: 'NA', label: 'Намибия'},
    {value: 'NR', label: 'Науру'},
    {value: 'NP', label: 'Непал'},
    {value: 'NL', label: 'Нидерланды'},
    {value: 'AN', label: 'Нидерландские Антильские острова'},
    {value: 'NC', label: 'Новая Каледония'},
    {value: 'NZ', label: 'Новая Зеландия'},
    {value: 'NI', label: 'Никарагуа'},
    {value: 'NE', label: 'Нигер'},
    {value: 'NG', label: 'Нигерия'},
    {value: 'NU', label: 'Ниуэ'},
    {value: 'NF', label: 'Остров Норфолк'},
    {value: 'MP', label: 'Северные Марианские острова'},
    {value: 'NO', label: 'Норвегия'},
    {value: 'OM', label: 'Оман'},
    {value: 'PK', label: 'Пакистан'},
    {value: 'PW', label: 'Палау'},
    {value: 'PS', label: 'Палестинская территория'},
    {value: 'PA', label: 'Панама'},
    {value: 'PG', label: 'Папуа — Новая Гвинея'},
    {value: 'PY', label: 'Парагвай'},
    {value: 'PE', label: 'Перу'},
    {value: 'PH', label: 'Филиппины'},
    {value: 'PN', label: 'Питкэрн'},
    {value: 'PL', label: 'Польша'},
    {value: 'PT', label: 'Португалия'},
    {value: 'PR', label: 'Пуэрто-Рико'},
    {value: 'QA', label: 'Катар'},
    {value: 'RE', label: 'Реюньон'},
    {value: 'RO', label: 'Румыния'},
    {value: 'RU', label: 'Российская Федерация'},
    {value: 'RW', label: 'Руанда'},
    {value: 'BL', label: 'Сен-Бартелеми'},
    {value: 'SH', label: 'Остров Святой Елены'},
    {value: 'KN', label: 'Сент-Китс и Невис'},
    {value: 'LC', label: 'Сент-Люсия'},
    {value: 'MF', label: 'Сен-Мартен'},
    {value: 'PM', label: 'Сен-Пьер и Микелон'},
    {value: 'VC', label: 'Сент-Винсент и Гренадины'},
    {value: 'WS', label: 'Самоа'},
    {value: 'SM', label: 'Сан-Марино'},
    {value: 'ST', label: 'Сан-Томе и Принсипи'},
    {value: 'SA', label: 'Саудовская Аравия'},
    {value: 'SN', label: 'Сенегал'},
    {value: 'RS', label: 'Сербия'},
    {value: 'SC', label: 'Сейшельские Острова'},
    {value: 'SL', label: 'Сьерра-Леоне'},
    {value: 'SG', label: 'Сингапур'},
    {value: 'SK', label: 'Словакия'},
    {value: 'SI', label: 'Словения'},
    {value: 'SB', label: 'Соломоновы Острова'},
    {value: 'SO', label: 'Сомали'},
    {value: 'ZA', label: 'Южно-Африканская Республика'},
    {value: 'GS', label: 'Южная Георгия и Южные Сандвичевы острова'},
    {value: 'ES', label: 'Испания'},
    {value: 'LK', label: 'Шри-Ланка'},
    {value: 'SD', label: 'Судан'},
    {value: 'SR', label: 'Суринам'},
    {value: 'SJ', label: 'Шпицберген и Ян-Майен'},
    {value: 'SZ', label: 'Эсватини'},
    {value: 'SE', label: 'Швеция'},
    {value: 'CH', label: 'Швейцария'},
    {value: 'SY', label: 'Сирийская Арабская Республика'},
    {value: 'TW', label: 'Тайвань'},
    {value: 'TJ', label: 'Таджикистан'},
    {value: 'TZ', label: 'Танзания'},
    {value: 'TH', label: 'Таиланд'},
    {value: 'TL', label: 'Восточный Тимор'},
    {value: 'TG', label: 'Того'},
    {value: 'TK', label: 'Токелау'},
    {value: 'TO', label: 'Тонга'},
    {value: 'TT', label: 'Тринидад и Тобаго'},
    {value: 'TN', label: 'Тунис'},
    {value: 'TR', label: 'Турция'},
    {value: 'TM', label: 'Туркменистан'},
    {value: 'TC', label: 'Теркс и Кайкос'},
    {value: 'TV', label: 'Тувалу'},
    {value: 'UG', label: 'Уганда'},
    {value: 'UA', label: 'Украина'},
    {value: 'AE', label: 'Объединенные Арабские Эмираты'},
    {value: 'GB', label: 'Великобритания'},
    {value: 'US', label: 'Соединенные Штаты'},
    {value: 'UM', label: 'Внешние малые острова США'},
    {value: 'UY', label: 'Уругвай'},
    {value: 'UZ', label: 'Узбекистан'},
    {value: 'VU', label: 'Вануату'},
    {value: 'VE', label: 'Венесуэла'},
    {value: 'VN', label: 'Вьетнам'},
    {value: 'VG', label: 'Виргинские острова, Британские'},
    {value: 'VI', label: 'Виргинские острова, США'},
    {value: 'WF', label: 'Уоллис и Футуна'},
    {value: 'EH', label: 'Западная Сахара'},
    {value: 'YE', label: 'Йемен'},
    {value: 'ZM', label: 'Замбия'},
    {value: 'ZW', label: 'Зимбабве'}
];