name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.8.1
      with:
        node-version: '18.16.0'

    - name: Install dependecies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Docker login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: .
        push: true
        tags: filatovtech/pigeoner-react

    - name: SSH Deploy
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secret.SERVER_HOST }}
        username: ${{ secret.SERVER_USERNAME }}
        key: ${{ secret.SSH_PRIVATE_KEY }}
        passphrase: ${{ secret.SSH_PASSPHRASE }}
        script: |
          sudo docker stop pigeoner-react
          sudo docker rm pigeoner-react
          sudo docker pull filatovtech/pigeoner-react
          sudo docker run -d --restart unless-stopped -it -p 81:80 --name pigeoner-react filatovtech/pigeoner-react
          



